version: '1'
services:
  waiter:
    image: restaurant:waiter-latest
    depends_on:
      - keycloak
    ports:
      - 8080:8080
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: restaurant
      POSTGRES_PASSWORD: restaurant
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - D:/PostgresData:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:16.1.1
    ports:
      - 6080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=restaurant
      - DB_VENDOR=postgres
      - DB_USER=restaurant
      - DB_PASSWORD=restaurant
      - DB_ADDR=db
      - DB_DATABASE=mydb
      - DB_PORT=5432
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    volumes:
      - ${PWD}/realm-export:/tmp
    depends_on:
      - db