version: '2'
services:
  waiter:
    image: restaurant:waiter-latest
    depends_on:
      - keycloak
    ports:
      - 8080:8080
    logging:
      driver: gelf
      options:
        gelf-address: "udp://restaurant:12201"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: restaurant
      POSTGRES_PASSWORD: restaurant
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - D:/PostgresData:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:16.1.1
    ports:
      - 6080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=restaurant
      - DB_VENDOR=postgres
      - DB_USER=restaurant
      - DB_PASSWORD=restaurant
      - DB_ADDR=db
      - DB_DATABASE=mydb
      - DB_PORT=5432
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    volumes:
      - ${PWD}/realm-export:/tmp
    depends_on:
      - db
  mongo:
    image: mongo:4.2
    volumes:
      - D:/mongo:/data/db
      #      networks:
      #        - graylog
      # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - D:/elastic:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 500m
  graylog:
    image: graylog/graylog:4.2
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://restaurant:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    #      networks:
    #        - graylog
    #      restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp